# Reset Settings Build Configuration
include:
  - board: nice_nano_v2
    shield: lily58_left
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_KEYBOARD_NAME="Reset Settings Left"
  - board: nice_nano_v2
    shield: lily58_right  
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_KEYBOARD_NAME="Reset Settings Right"